In [1]:
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
!pip install transformers datasets
!pip install peft
!pip install evaluate scikit-learn transformers[torch]
!pip install accelerate>=0.26.0

Looking in indexes: https://download.pytorch.org/whl/cu121
Requirement already satisfied: torch in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (2.5.1+cu121)
Requirement already satisfied: torchvision in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (0.20.1+cu121)
Requirement already satisfied: torchaudio in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (2.5.1+cu121)
Requirement already satisfied: filelock in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch) (3.19.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch) (4.16.0)
Requirement already satisfied: networkx in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch) (3.2.1)
Requirement already satisfied: jinja2 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch) (2025.10.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch) (12.1.105)
Requirement already satisfied: triton==3.1.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch) (1.13.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch) (12.8.93)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: numpy in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torchvision) (2.0.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torchvision) (11.3.0)

Requirement already satisfied: MarkupSafe>=2.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from jinja2->torch) (3.0.4)

Requirement already satisfied: transformers in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (4.57.6)
Requirement already satisfied: datasets in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (4.5.0)

Requirement already satisfied: filelock in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from transformers) (3.19.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from transformers) (0.36.2)
Requirement already satisfied: numpy>=1.17 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from transformers) (26.3)
Requirement already satisfied: pyyaml>=5.1 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from transformers) (2026.1.15)
Requirement already satisfied: requests in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from transformers) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from transformers) (4.70.1)
Requirement already satisfied: fsspec>=2023.5.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.10.0)

Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.7.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.16.0)
Requirement already satisfied: pyarrow>=21.0.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from datasets) (21.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from datasets) (0.4.0)
Requirement already satisfied: pandas in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from datasets) (2.3.3)
Requirement already satisfied: httpx<1.0.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from datasets) (4.0.1)
Requirement already satisfied: multiprocess<0.70.19 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from datasets) (0.70.18)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: anyio in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from httpx<1.0.0->datasets) (2026.10.18)
Requirement already satisfied: httpcore==1.* in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from httpx<1.0.0->datasets) (3.20)

Requirement already satisfied: h11>=0.16 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from requests->transformers) (3.5.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from requests->transformers) (2.6.3)
Requirement already satisfied: exceptiongroup>=1.0.2 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from pandas->datasets) (2.9.0.post0)

Requirement already satisfied: pytz>=2020.1 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from pandas->datasets) (2026.5)
Requirement already satisfied: tzdata>=2022.7 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from pandas->datasets) (2026.5)
Requirement already satisfied: six>=1.5 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

Requirement already satisfied: peft in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (0.17.1)

Requirement already satisfied: numpy>=1.17 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from peft) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from peft) (26.3)
Requirement already satisfied: psutil in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from peft) (7.2.2)
Requirement already satisfied: pyyaml in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from peft) (6.0.3)
Requirement already satisfied: torch>=1.13.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from peft) (2.5.1+cu121)
Requirement already satisfied: transformers in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from peft) (4.57.6)
Requirement already satisfied: tqdm in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from peft) (4.70.1)
Requirement already satisfied: accelerate>=0.21.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from peft) (1.10.1)
Requirement already satisfied: safetensors in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from peft) (0.7.0)
Requirement already satisfied: huggingface_hub>=0.25.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from peft) (0.36.2)
Requirement already satisfied: filelock in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from huggingface_hub>=0.25.0->peft) (3.19.1)
Requirement already satisfied: fsspec>=2023.5.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from huggingface_hub>=0.25.0->peft) (2025.10.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from huggingface_hub>=0.25.0->peft) (1.7.0)
Requirement already satisfied: requests in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from huggingface_hub>=0.25.0->peft) (2.32.5)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from huggingface_hub>=0.25.0->peft) (4.16.0)

Requirement already satisfied: networkx in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=1.13.0->peft) (3.2.1)
Requirement already satisfied: jinja2 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=1.13.0->peft) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=1.13.0->peft) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=1.13.0->peft) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=1.13.0->peft) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=1.13.0->peft) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=1.13.0->peft) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=1.13.0->peft) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=1.13.0->peft) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=1.13.0->peft) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=1.13.0->peft) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=1.13.0->peft) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=1.13.0->peft) (12.1.105)
Requirement already satisfied: triton==3.1.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=1.13.0->peft) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=1.13.0->peft) (1.13.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from sympy==1.13.1->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from jinja2->torch>=1.13.0->peft) (3.0.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from requests->huggingface_hub>=0.25.0->peft) (3.5.2)
Requirement already satisfied: idna<4,>=2.5 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from requests->huggingface_hub>=0.25.0->peft) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from requests->huggingface_hub>=0.25.0->peft) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from requests->huggingface_hub>=0.25.0->peft) (2026.10.18)

Requirement already satisfied: regex!=2019.12.17 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from transformers->peft) (2026.1.15)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from transformers->peft) (0.22.2)

Requirement already satisfied: evaluate in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (0.4.6)
Requirement already satisfied: scikit-learn in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (1.6.1)
Requirement already satisfied: transformers[torch] in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (4.57.6)

Requirement already satisfied: datasets>=2.0.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from evaluate) (4.5.0)
Requirement already satisfied: numpy>=1.17 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from evaluate) (0.4.0)
Requirement already satisfied: pandas in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from evaluate) (2.3.3)
Requirement already satisfied: requests>=2.19.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from evaluate) (2.32.5)
Requirement already satisfied: tqdm>=4.62.1 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from evaluate) (4.70.1)
Requirement already satisfied: xxhash in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from evaluate) (4.0.1)
Requirement already satisfied: multiprocess in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from evaluate) (0.70.18)
Requirement already satisfied: fsspec>=2021.05.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.10.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from evaluate) (0.36.2)
Requirement already satisfied: packaging in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from evaluate) (26.3)
Requirement already satisfied: scipy>=1.6.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: joblib>=1.2.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from scikit-learn) (3.7.0)

Requirement already satisfied: filelock in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from transformers[torch]) (3.19.1)
Requirement already satisfied: pyyaml>=5.1 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from transformers[torch]) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from transformers[torch]) (2026.1.15)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from transformers[torch]) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from transformers[torch]) (0.7.0)
Requirement already satisfied: torch>=2.2 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from transformers[torch]) (2.5.1+cu121)
Requirement already satisfied: accelerate>=0.26.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from transformers[torch]) (1.10.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from huggingface-hub>=0.7.0->evaluate) (1.7.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from huggingface-hub>=0.7.0->evaluate) (4.16.0)
Requirement already satisfied: psutil in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from accelerate>=0.26.0->transformers[torch]) (7.2.2)

Requirement already satisfied: pyarrow>=21.0.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from datasets>=2.0.0->evaluate) (21.0.0)
Requirement already satisfied: httpx<1.0.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from datasets>=2.0.0->evaluate) (0.28.1)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from fsspec[http]>=2021.05.0->evaluate) (3.13.5)
Requirement already satisfied: anyio in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (4.12.1)
Requirement already satisfied: certifi in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (2026.10.18)
Requirement already satisfied: httpcore==1.* in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (1.0.9)
Requirement already satisfied: idna in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from httpx<1.0.0->datasets>=2.0.0->evaluate) (3.20)
Requirement already satisfied: h11>=0.16 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from httpcore==1.*->httpx<1.0.0->datasets>=2.0.0->evaluate) (0.16.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: async-timeout<6.0,>=4.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.22.0)

Requirement already satisfied: charset_normalizer<4,>=2 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from requests>=2.19.0->evaluate) (3.5.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from requests>=2.19.0->evaluate) (2.6.3)
Requirement already satisfied: networkx in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=2.2->transformers[torch]) (3.2.1)
Requirement already satisfied: jinja2 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=2.2->transformers[torch]) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=2.2->transformers[torch]) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=2.2->transformers[torch]) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=2.2->transformers[torch]) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=2.2->transformers[torch]) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=2.2->transformers[torch]) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=2.2->transformers[torch]) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=2.2->transformers[torch]) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=2.2->transformers[torch]) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=2.2->transformers[torch]) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=2.2->transformers[torch]) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=2.2->transformers[torch]) (12.1.105)
Requirement already satisfied: triton==3.1.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=2.2->transformers[torch]) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from torch>=2.2->transformers[torch]) (1.13.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=2.2->transformers[torch]) (12.8.93)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from sympy==1.13.1->torch>=2.2->transformers[torch]) (1.3.0)
Requirement already satisfied: exceptiongroup>=1.0.2 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from anyio->httpx<1.0.0->datasets>=2.0.0->evaluate) (1.3.1)

Requirement already satisfied: MarkupSafe>=2.0 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from jinja2->torch>=2.2->transformers[torch]) (3.0.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from pandas->evaluate) (2026.5)
Requirement already satisfied: tzdata>=2022.7 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from pandas->evaluate) (2026.5)
Requirement already satisfied: six>=1.5 in /tmp/mdiop_tp5/env/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)

# Prepare the dataset

In [2]:
from datasets import load_dataset

imdb = load_dataset("stanfordnlp/imdb")
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")


def tokenize_function(examples):
    return tokenizer(examples["text"], padding="max_length", truncation=True)


tokenized_datasets = imdb.map(tokenize_function, batched=True)

/tmp/mdiop_tp5/env/lib64/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Map:   0%|          | 0/25000 [00:00<?, ? examples/s]

Map:   4%|▍         | 1000/25000 [00:00<00:04, 5208.37 examples/s]

Map:   8%|▊         | 2000/25000 [00:00<00:04, 5160.66 examples/s]

Map:  12%|█▏        | 3000/25000 [00:00<00:04, 5135.09 examples/s]

Map:  16%|█▌        | 4000/25000 [00:00<00:04, 5139.34 examples/s]

Map:  20%|██        | 5000/25000 [00:00<00:03, 5131.82 examples/s]

Map:  24%|██▍       | 6000/25000 [00:01<00:03, 5095.37 examples/s]

Map:  28%|██▊       | 7000/25000 [00:01<00:03, 5116.58 examples/s]

Map:  32%|███▏      | 8000/25000 [00:01<00:03, 5104.92 examples/s]

Map:  36%|███▌      | 9000/25000 [00:01<00:03, 4550.07 examples/s]

Map:  40%|████      | 10000/25000 [00:02<00:03, 4731.19 examples/s]

Map:  44%|████▍     | 11000/25000 [00:02<00:02, 4837.71 examples/s]

Map:  48%|████▊     | 12000/25000 [00:02<00:02, 4899.23 examples/s]

Map:  52%|█████▏    | 13000/25000 [00:02<00:02, 4958.04 examples/s]

Map:  56%|█████▌    | 14000/25000 [00:02<00:02, 4990.36 examples/s]

Map:  60%|██████    | 15000/25000 [00:03<00:01, 5012.87 examples/s]

Map:  64%|██████▍   | 16000/25000 [00:03<00:01, 5016.94 examples/s]

Map:  68%|██████▊   | 17000/25000 [00:03<00:01, 5037.19 examples/s]

Map:  72%|███████▏  | 18000/25000 [00:03<00:01, 5024.18 examples/s]

Map:  76%|███████▌  | 19000/25000 [00:03<00:01, 5033.70 examples/s]

Map:  80%|████████  | 20000/25000 [00:04<00:00, 5058.83 examples/s]

Map:  84%|████████▍ | 21000/25000 [00:04<00:00, 5076.30 examples/s]

Map:  88%|████████▊ | 22000/25000 [00:04<00:00, 5088.93 examples/s]

Map:  92%|█████████▏| 23000/25000 [00:04<00:00, 5073.75 examples/s]

Map:  96%|█████████▌| 24000/25000 [00:04<00:00, 5091.40 examples/s]

Map: 100%|██████████| 25000/25000 [00:04<00:00, 5103.11 examples/s]

Map: 100%|██████████| 25000/25000 [00:04<00:00, 5012.46 examples/s]

In [3]:
training_set = tokenized_datasets['train'].shuffle(42).select(range(5000))
shuffled_set =  tokenized_datasets['test'].shuffle(42)
validation_set  = shuffled_set.select(range(1000))
test_set = shuffled_set.select(range(1000, 2000))

## First method : Using the transformers library and pytorch

In [4]:
from transformers import BertTokenizer
from transformers import BertForSequenceClassification

## Fine-tuning the whole model

In [5]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForSequenceClassification.from_pretrained('bert-base-cased', num_labels=2)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [6]:
import numpy as np
import evaluate

metric = evaluate.load("accuracy")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

In [7]:
import copy
from transformers import TrainingArguments, Trainer

def count_trainable_parameters(model):
    count = 0
    for parameter in model.parameters():
        if parameter.requires_grad:
            count = count + parameter.numel()
    return count

# we fine-tune a copy, so that model stays the pretrained BERT used for LoRA below
full_model = copy.deepcopy(model)

# same training arguments as for LoRA below, to compare the approaches fairly
training_args = TrainingArguments(output_dir="test_full_finetuning",
                                  eval_strategy="steps",
                                  eval_steps= 128,
                                  num_train_epochs=2,)
full_trainer = Trainer(
    model=full_model,
    args=training_args,
    train_dataset= training_set,
    eval_dataset=validation_set,
    compute_metrics=compute_metrics,
)
full_train_output = full_trainer.train()
full_test_results = full_trainer.evaluate(test_set)
print("Trainable parameters:", count_trainable_parameters(full_model))
print("Test accuracy:", full_test_results["eval_accuracy"])

Trainable parameters: 108311810
Test accuracy: 0.909

## LoRA implementation

In [8]:
[k for k,v  in model.bert.named_parameters()]

['embeddings.word_embeddings.weight',
 'embeddings.position_embeddings.weight',
 'embeddings.token_type_embeddings.weight',
 'embeddings.LayerNorm.weight',
 'embeddings.LayerNorm.bias',
 'encoder.layer.0.attention.self.query.weight',
 'encoder.layer.0.attention.self.query.bias',
 'encoder.layer.0.attention.self.key.weight',
 'encoder.layer.0.attention.self.key.bias',
 'encoder.layer.0.attention.self.value.weight',
 'encoder.layer.0.attention.self.value.bias',
 'encoder.layer.0.attention.output.dense.weight',
 'encoder.layer.0.attention.output.dense.bias',
 'encoder.layer.0.attention.output.LayerNorm.weight',
 'encoder.layer.0.attention.output.LayerNorm.bias',
 'encoder.layer.0.intermediate.dense.weight',
 'encoder.layer.0.intermediate.dense.bias',
 'encoder.layer.0.output.dense.weight',
 'encoder.layer.0.output.dense.bias',
 'encoder.layer.0.output.LayerNorm.weight',
 'encoder.layer.0.output.LayerNorm.bias',
 'encoder.layer.1.attention.self.query.weight',
 'encoder.layer.1.attention.self.query.bias',
 'encoder.layer.1.attention.self.key.weight',
 'encoder.layer.1.attention.self.key.bias',
 'encoder.layer.1.attention.self.value.weight',
 'encoder.layer.1.attention.self.value.bias',
 'encoder.layer.1.attention.output.dense.weight',
 'encoder.layer.1.attention.output.dense.bias',
 'encoder.layer.1.attention.output.LayerNorm.weight',
 'encoder.layer.1.attention.output.LayerNorm.bias',
 'encoder.layer.1.intermediate.dense.weight',
 'encoder.layer.1.intermediate.dense.bias',
 'encoder.layer.1.output.dense.weight',
 'encoder.layer.1.output.dense.bias',
 'encoder.layer.1.output.LayerNorm.weight',
 'encoder.layer.1.output.LayerNorm.bias',
 'encoder.layer.2.attention.self.query.weight',
 'encoder.layer.2.attention.self.query.bias',
 'encoder.layer.2.attention.self.key.weight',
 'encoder.layer.2.attention.self.key.bias',
 'encoder.layer.2.attention.self.value.weight',
 'encoder.layer.2.attention.self.value.bias',
 'encoder.layer.2.attention.output.dense.weight',
 'encoder.layer.2.attention.output.dense.bias',
 'encoder.layer.2.attention.output.LayerNorm.weight',
 'encoder.layer.2.attention.output.LayerNorm.bias',
 'encoder.layer.2.intermediate.dense.weight',
 'encoder.layer.2.intermediate.dense.bias',
 'encoder.layer.2.output.dense.weight',
 'encoder.layer.2.output.dense.bias',
 'encoder.layer.2.output.LayerNorm.weight',
 'encoder.layer.2.output.LayerNorm.bias',
 'encoder.layer.3.attention.self.query.weight',
 'encoder.layer.3.attention.self.query.bias',
 'encoder.layer.3.attention.self.key.weight',
 'encoder.layer.3.attention.self.key.bias',
 'encoder.layer.3.attention.self.value.weight',
 'encoder.layer.3.attention.self.value.bias',
 'encoder.layer.3.attention.output.dense.weight',
 'encoder.layer.3.attention.output.dense.bias',
 'encoder.layer.3.attention.output.LayerNorm.weight',
 'encoder.layer.3.attention.output.LayerNorm.bias',
 'encoder.layer.3.intermediate.dense.weight',
 'encoder.layer.3.intermediate.dense.bias',
 'encoder.layer.3.output.dense.weight',
 'encoder.layer.3.output.dense.bias',
 'encoder.layer.3.output.LayerNorm.weight',
 'encoder.layer.3.output.LayerNorm.bias',
 'encoder.layer.4.attention.self.query.weight',
 'encoder.layer.4.attention.self.query.bias',
 'encoder.layer.4.attention.self.key.weight',
 'encoder.layer.4.attention.self.key.bias',
 'encoder.layer.4.attention.self.value.weight',
 'encoder.layer.4.attention.self.value.bias',
 'encoder.layer.4.attention.output.dense.weight',
 'encoder.layer.4.attention.output.dense.bias',
 'encoder.layer.4.attention.output.LayerNorm.weight',
 'encoder.layer.4.attention.output.LayerNorm.bias',
 'encoder.layer.4.intermediate.dense.weight',
 'encoder.layer.4.intermediate.dense.bias',
 'encoder.layer.4.output.dense.weight',
 'encoder.layer.4.output.dense.bias',
 'encoder.layer.4.output.LayerNorm.weight',
 'encoder.layer.4.output.LayerNorm.bias',
 'encoder.layer.5.attention.self.query.weight',
 'encoder.layer.5.attention.self.query.bias',
 'encoder.layer.5.attention.self.key.weight',
 'encoder.layer.5.attention.self.key.bias',
 'encoder.layer.5.attention.self.value.weight',
 'encoder.layer.5.attention.self.value.bias',
 'encoder.layer.5.attention.output.dense.weight',
 'encoder.layer.5.attention.output.dense.bias',
 'encoder.layer.5.attention.output.LayerNorm.weight',
 'encoder.layer.5.attention.output.LayerNorm.bias',
 'encoder.layer.5.intermediate.dense.weight',
 'encoder.layer.5.intermediate.dense.bias',
 'encoder.layer.5.output.dense.weight',
 'encoder.layer.5.output.dense.bias',
 'encoder.layer.5.output.LayerNorm.weight',
 'encoder.layer.5.output.LayerNorm.bias',
 'encoder.layer.6.attention.self.query.weight',
 'encoder.layer.6.attention.self.query.bias',
 'encoder.layer.6.attention.self.key.weight',
 'encoder.layer.6.attention.self.key.bias',
 'encoder.layer.6.attention.self.value.weight',
 'encoder.layer.6.attention.self.value.bias',
 'encoder.layer.6.attention.output.dense.weight',
 'encoder.layer.6.attention.output.dense.bias',
 'encoder.layer.6.attention.output.LayerNorm.weight',
 'encoder.layer.6.attention.output.LayerNorm.bias',
 'encoder.layer.6.intermediate.dense.weight',
 'encoder.layer.6.intermediate.dense.bias',
 'encoder.layer.6.output.dense.weight',
 'encoder.layer.6.output.dense.bias',
 'encoder.layer.6.output.LayerNorm.weight',
 'encoder.layer.6.output.LayerNorm.bias',
 'encoder.layer.7.attention.self.query.weight',
 'encoder.layer.7.attention.self.query.bias',
 'encoder.layer.7.attention.self.key.weight',
 'encoder.layer.7.attention.self.key.bias',
 'encoder.layer.7.attention.self.value.weight',
 'encoder.layer.7.attention.self.value.bias',
 'encoder.layer.7.attention.output.dense.weight',
 'encoder.layer.7.attention.output.dense.bias',
 'encoder.layer.7.attention.output.LayerNorm.weight',
 'encoder.layer.7.attention.output.LayerNorm.bias',
 'encoder.layer.7.intermediate.dense.weight',
 'encoder.layer.7.intermediate.dense.bias',
 'encoder.layer.7.output.dense.weight',
 'encoder.layer.7.output.dense.bias',
 'encoder.layer.7.output.LayerNorm.weight',
 'encoder.layer.7.output.LayerNorm.bias',
 'encoder.layer.8.attention.self.query.weight',
 'encoder.layer.8.attention.self.query.bias',
 'encoder.layer.8.attention.self.key.weight',
 'encoder.layer.8.attention.self.key.bias',
 'encoder.layer.8.attention.self.value.weight',
 'encoder.layer.8.attention.self.value.bias',
 'encoder.layer.8.attention.output.dense.weight',
 'encoder.layer.8.attention.output.dense.bias',
 'encoder.layer.8.attention.output.LayerNorm.weight',
 'encoder.layer.8.attention.output.LayerNorm.bias',
 'encoder.layer.8.intermediate.dense.weight',
 'encoder.layer.8.intermediate.dense.bias',
 'encoder.layer.8.output.dense.weight',
 'encoder.layer.8.output.dense.bias',
 'encoder.layer.8.output.LayerNorm.weight',
 'encoder.layer.8.output.LayerNorm.bias',
 'encoder.layer.9.attention.self.query.weight',
 'encoder.layer.9.attention.self.query.bias',
 'encoder.layer.9.attention.self.key.weight',
 'encoder.layer.9.attention.self.key.bias',
 'encoder.layer.9.attention.self.value.weight',
 'encoder.layer.9.attention.self.value.bias',
 'encoder.layer.9.attention.output.dense.weight',
 'encoder.layer.9.attention.output.dense.bias',
 'encoder.layer.9.attention.output.LayerNorm.weight',
 'encoder.layer.9.attention.output.LayerNorm.bias',
 'encoder.layer.9.intermediate.dense.weight',
 'encoder.layer.9.intermediate.dense.bias',
 'encoder.layer.9.output.dense.weight',
 'encoder.layer.9.output.dense.bias',
 'encoder.layer.9.output.LayerNorm.weight',
 'encoder.layer.9.output.LayerNorm.bias',
 'encoder.layer.10.attention.self.query.weight',
 'encoder.layer.10.attention.self.query.bias',
 'encoder.layer.10.attention.self.key.weight',
 'encoder.layer.10.attention.self.key.bias',
 'encoder.layer.10.attention.self.value.weight',
 'encoder.layer.10.attention.self.value.bias',
 'encoder.layer.10.attention.output.dense.weight',
 'encoder.layer.10.attention.output.dense.bias',
 'encoder.layer.10.attention.output.LayerNorm.weight',
 'encoder.layer.10.attention.output.LayerNorm.bias',
 'encoder.layer.10.intermediate.dense.weight',
 'encoder.layer.10.intermediate.dense.bias',
 'encoder.layer.10.output.dense.weight',
 'encoder.layer.10.output.dense.bias',
 'encoder.layer.10.output.LayerNorm.weight',
 'encoder.layer.10.output.LayerNorm.bias',
 'encoder.layer.11.attention.self.query.weight',
 'encoder.layer.11.attention.self.query.bias',
 'encoder.layer.11.attention.self.key.weight',
 'encoder.layer.11.attention.self.key.bias',
 'encoder.layer.11.attention.self.value.weight',
 'encoder.layer.11.attention.self.value.bias',
 'encoder.layer.11.attention.output.dense.weight',
 'encoder.layer.11.attention.output.dense.bias',
 'encoder.layer.11.attention.output.LayerNorm.weight',
 'encoder.layer.11.attention.output.LayerNorm.bias',
 'encoder.layer.11.intermediate.dense.weight',
 'encoder.layer.11.intermediate.dense.bias',
 'encoder.layer.11.output.dense.weight',
 'encoder.layer.11.output.dense.bias',
 'encoder.layer.11.output.LayerNorm.weight',
 'encoder.layer.11.output.LayerNorm.bias',
 'pooler.dense.weight',
 'pooler.dense.bias']

In [9]:
print(f"What is the model \n\n {model}")

What is the model

 BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(28996, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
)

### Create the LoRA module

We will consider in this module the original linear, and the down and up projection

In [10]:
import torch 
import copy
from torch import nn

class LoRALinear(nn.Module):
  def __init__(
    self, in_dim: int, out_dim: int, rank: int
  ):
    super().__init__()
    self.linear = nn.Linear(in_dim, out_dim)
    # Q = W x + B (A x), with A of size rank x in_dim and B of size out_dim x rank
    self.lora_a = nn.Linear(in_dim, rank, bias=False)
    self.lora_b = nn.Linear(rank, out_dim, bias=False)
    # B starts at zero as in the LoRA paper: at the beginning the output is exactly the pretrained one
    nn.init.zeros_(self.lora_b.weight)

  def forward(self, x: torch.Tensor) -> torch.Tensor:
    frozen_out = self.linear(x)
    lora_out = self.lora_b(self.lora_a(x))
    return frozen_out + lora_out

### Create a function replacing linear by lora module
From the original Linear module return a LoRA module
* The linear of the LoRA linear must be initialised with pretrained weights

In [11]:


def linear_to_lora(linear):
    linear_weight = linear.weight.data
    has_bias = linear.bias is not None
    if has_bias:
        linear_bias = linear.bias.data
    output_size, input_size =  linear_weight.shape
    lora = LoRALinear(input_size, output_size, rank=8)
    lora.linear.weight.data = linear_weight
    if has_bias:
        lora.linear.bias.data = linear_bias
    return lora

We now replace the target linear by the LoRALinear described above

In [12]:
lora_model = copy.deepcopy(model)
lora_parameters = []
for block in lora_model.bert.encoder.layer:
    # as in the course, the key, value and query projections of each self-attention are adapted
    block.attention.self.key = linear_to_lora(block.attention.self.key)
    block.attention.self.value = linear_to_lora(block.attention.self.value)
    block.attention.self.query = linear_to_lora(block.attention.self.query)

In [13]:
print(f"What is the model modified with LoRA: \n\n {lora_model}")

What is the model modified with LoRA:

 BertForSequenceClassification(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(28996, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): LoRALinear(
                (linear): Linear(in_features=768, out_features=768, bias=True)
                (lora_a): Linear(in_features=768, out_features=8, bias=False)
                (lora_b): Linear(in_features=8, out_features=768, bias=False)
              )
              (key): LoRALinear(
                (linear): Linear(in_features=768, out_features=768, bias=True)
                (lora_a): Linear(in_features=768, out_features=8, bias=False)
                (lora_b): Linear(in_features=8, out_features=768, bias=False)
              )
              (value): LoRALinear(
                (linear): Linear(in_features=768, out_features=768, bias=True)
                (lora_a): Linear(in_features=768, out_features=8, bias=False)
                (lora_b): Linear(in_features=8, out_features=768, bias=False)
              )
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (dropout): Dropout(p=0.1, inplace=False)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
)

### Defining module requiring grad

In [14]:
for k,v  in lora_model.bert.named_parameters():
    print(k)
    if ('lora' in k):
        v.requires_grad = True
    else:
        v.requires_grad = False

embeddings.word_embeddings.weight
embeddings.position_embeddings.weight
embeddings.token_type_embeddings.weight
embeddings.LayerNorm.weight
embeddings.LayerNorm.bias
encoder.layer.0.attention.self.query.linear.weight
encoder.layer.0.attention.self.query.linear.bias
encoder.layer.0.attention.self.query.lora_a.weight
encoder.layer.0.attention.self.query.lora_b.weight
encoder.layer.0.attention.self.key.linear.weight
encoder.layer.0.attention.self.key.linear.bias
encoder.layer.0.attention.self.key.lora_a.weight
encoder.layer.0.attention.self.key.lora_b.weight
encoder.layer.0.attention.self.value.linear.weight
encoder.layer.0.attention.self.value.linear.bias
encoder.layer.0.attention.self.value.lora_a.weight
encoder.layer.0.attention.self.value.lora_b.weight
encoder.layer.0.attention.output.dense.weight
encoder.layer.0.attention.output.dense.bias
encoder.layer.0.attention.output.LayerNorm.weight
encoder.layer.0.attention.output.LayerNorm.bias
encoder.layer.0.intermediate.dense.weight
encoder.layer.0.intermediate.dense.bias
encoder.layer.0.output.dense.weight
encoder.layer.0.output.dense.bias
encoder.layer.0.output.LayerNorm.weight
encoder.layer.0.output.LayerNorm.bias
encoder.layer.1.attention.self.query.linear.weight
encoder.layer.1.attention.self.query.linear.bias
encoder.layer.1.attention.self.query.lora_a.weight
encoder.layer.1.attention.self.query.lora_b.weight
encoder.layer.1.attention.self.key.linear.weight
encoder.layer.1.attention.self.key.linear.bias
encoder.layer.1.attention.self.key.lora_a.weight
encoder.layer.1.attention.self.key.lora_b.weight
encoder.layer.1.attention.self.value.linear.weight
encoder.layer.1.attention.self.value.linear.bias
encoder.layer.1.attention.self.value.lora_a.weight
encoder.layer.1.attention.self.value.lora_b.weight
encoder.layer.1.attention.output.dense.weight
encoder.layer.1.attention.output.dense.bias
encoder.layer.1.attention.output.LayerNorm.weight
encoder.layer.1.attention.output.LayerNorm.bias
encoder.layer.1.intermediate.dense.weight
encoder.layer.1.intermediate.dense.bias
encoder.layer.1.output.dense.weight
encoder.layer.1.output.dense.bias
encoder.layer.1.output.LayerNorm.weight
encoder.layer.1.output.LayerNorm.bias
encoder.layer.2.attention.self.query.linear.weight
encoder.layer.2.attention.self.query.linear.bias
encoder.layer.2.attention.self.query.lora_a.weight
encoder.layer.2.attention.self.query.lora_b.weight
encoder.layer.2.attention.self.key.linear.weight
encoder.layer.2.attention.self.key.linear.bias
encoder.layer.2.attention.self.key.lora_a.weight
encoder.layer.2.attention.self.key.lora_b.weight
encoder.layer.2.attention.self.value.linear.weight
encoder.layer.2.attention.self.value.linear.bias
encoder.layer.2.attention.self.value.lora_a.weight
encoder.layer.2.attention.self.value.lora_b.weight
encoder.layer.2.attention.output.dense.weight
encoder.layer.2.attention.output.dense.bias
encoder.layer.2.attention.output.LayerNorm.weight
encoder.layer.2.attention.output.LayerNorm.bias
encoder.layer.2.intermediate.dense.weight
encoder.layer.2.intermediate.dense.bias
encoder.layer.2.output.dense.weight
encoder.layer.2.output.dense.bias
encoder.layer.2.output.LayerNorm.weight
encoder.layer.2.output.LayerNorm.bias
encoder.layer.3.attention.self.query.linear.weight
encoder.layer.3.attention.self.query.linear.bias
encoder.layer.3.attention.self.query.lora_a.weight
encoder.layer.3.attention.self.query.lora_b.weight
encoder.layer.3.attention.self.key.linear.weight
encoder.layer.3.attention.self.key.linear.bias
encoder.layer.3.attention.self.key.lora_a.weight
encoder.layer.3.attention.self.key.lora_b.weight
encoder.layer.3.attention.self.value.linear.weight
encoder.layer.3.attention.self.value.linear.bias
encoder.layer.3.attention.self.value.lora_a.weight
encoder.layer.3.attention.self.value.lora_b.weight
encoder.layer.3.attention.output.dense.weight
encoder.layer.3.attention.output.dense.bias
encoder.layer.3.attention.output.LayerNorm.weight
encoder.layer.3.attention.output.LayerNorm.bias
encoder.layer.3.intermediate.dense.weight
encoder.layer.3.intermediate.dense.bias
encoder.layer.3.output.dense.weight
encoder.layer.3.output.dense.bias
encoder.layer.3.output.LayerNorm.weight
encoder.layer.3.output.LayerNorm.bias
encoder.layer.4.attention.self.query.linear.weight
encoder.layer.4.attention.self.query.linear.bias
encoder.layer.4.attention.self.query.lora_a.weight
encoder.layer.4.attention.self.query.lora_b.weight
encoder.layer.4.attention.self.key.linear.weight
encoder.layer.4.attention.self.key.linear.bias
encoder.layer.4.attention.self.key.lora_a.weight
encoder.layer.4.attention.self.key.lora_b.weight
encoder.layer.4.attention.self.value.linear.weight
encoder.layer.4.attention.self.value.linear.bias
encoder.layer.4.attention.self.value.lora_a.weight
encoder.layer.4.attention.self.value.lora_b.weight
encoder.layer.4.attention.output.dense.weight
encoder.layer.4.attention.output.dense.bias
encoder.layer.4.attention.output.LayerNorm.weight
encoder.layer.4.attention.output.LayerNorm.bias
encoder.layer.4.intermediate.dense.weight
encoder.layer.4.intermediate.dense.bias
encoder.layer.4.output.dense.weight
encoder.layer.4.output.dense.bias
encoder.layer.4.output.LayerNorm.weight
encoder.layer.4.output.LayerNorm.bias
encoder.layer.5.attention.self.query.linear.weight
encoder.layer.5.attention.self.query.linear.bias
encoder.layer.5.attention.self.query.lora_a.weight
encoder.layer.5.attention.self.query.lora_b.weight
encoder.layer.5.attention.self.key.linear.weight
encoder.layer.5.attention.self.key.linear.bias
encoder.layer.5.attention.self.key.lora_a.weight
encoder.layer.5.attention.self.key.lora_b.weight
encoder.layer.5.attention.self.value.linear.weight
encoder.layer.5.attention.self.value.linear.bias
encoder.layer.5.attention.self.value.lora_a.weight
encoder.layer.5.attention.self.value.lora_b.weight
encoder.layer.5.attention.output.dense.weight
encoder.layer.5.attention.output.dense.bias
encoder.layer.5.attention.output.LayerNorm.weight
encoder.layer.5.attention.output.LayerNorm.bias
encoder.layer.5.intermediate.dense.weight
encoder.layer.5.intermediate.dense.bias
encoder.layer.5.output.dense.weight
encoder.layer.5.output.dense.bias
encoder.layer.5.output.LayerNorm.weight
encoder.layer.5.output.LayerNorm.bias
encoder.layer.6.attention.self.query.linear.weight
encoder.layer.6.attention.self.query.linear.bias
encoder.layer.6.attention.self.query.lora_a.weight
encoder.layer.6.attention.self.query.lora_b.weight
encoder.layer.6.attention.self.key.linear.weight
encoder.layer.6.attention.self.key.linear.bias
encoder.layer.6.attention.self.key.lora_a.weight
encoder.layer.6.attention.self.key.lora_b.weight
encoder.layer.6.attention.self.value.linear.weight
encoder.layer.6.attention.self.value.linear.bias
encoder.layer.6.attention.self.value.lora_a.weight
encoder.layer.6.attention.self.value.lora_b.weight
encoder.layer.6.attention.output.dense.weight
encoder.layer.6.attention.output.dense.bias
encoder.layer.6.attention.output.LayerNorm.weight
encoder.layer.6.attention.output.LayerNorm.bias
encoder.layer.6.intermediate.dense.weight
encoder.layer.6.intermediate.dense.bias
encoder.layer.6.output.dense.weight
encoder.layer.6.output.dense.bias
encoder.layer.6.output.LayerNorm.weight
encoder.layer.6.output.LayerNorm.bias
encoder.layer.7.attention.self.query.linear.weight
encoder.layer.7.attention.self.query.linear.bias
encoder.layer.7.attention.self.query.lora_a.weight
encoder.layer.7.attention.self.query.lora_b.weight
encoder.layer.7.attention.self.key.linear.weight
encoder.layer.7.attention.self.key.linear.bias
encoder.layer.7.attention.self.key.lora_a.weight
encoder.layer.7.attention.self.key.lora_b.weight
encoder.layer.7.attention.self.value.linear.weight
encoder.layer.7.attention.self.value.linear.bias
encoder.layer.7.attention.self.value.lora_a.weight
encoder.layer.7.attention.self.value.lora_b.weight
encoder.layer.7.attention.output.dense.weight
encoder.layer.7.attention.output.dense.bias
encoder.layer.7.attention.output.LayerNorm.weight
encoder.layer.7.attention.output.LayerNorm.bias
encoder.layer.7.intermediate.dense.weight
encoder.layer.7.intermediate.dense.bias
encoder.layer.7.output.dense.weight
encoder.layer.7.output.dense.bias
encoder.layer.7.output.LayerNorm.weight
encoder.layer.7.output.LayerNorm.bias
encoder.layer.8.attention.self.query.linear.weight
encoder.layer.8.attention.self.query.linear.bias
encoder.layer.8.attention.self.query.lora_a.weight
encoder.layer.8.attention.self.query.lora_b.weight
encoder.layer.8.attention.self.key.linear.weight
encoder.layer.8.attention.self.key.linear.bias
encoder.layer.8.attention.self.key.lora_a.weight
encoder.layer.8.attention.self.key.lora_b.weight
encoder.layer.8.attention.self.value.linear.weight
encoder.layer.8.attention.self.value.linear.bias
encoder.layer.8.attention.self.value.lora_a.weight
encoder.layer.8.attention.self.value.lora_b.weight
encoder.layer.8.attention.output.dense.weight
encoder.layer.8.attention.output.dense.bias
encoder.layer.8.attention.output.LayerNorm.weight
encoder.layer.8.attention.output.LayerNorm.bias
encoder.layer.8.intermediate.dense.weight
encoder.layer.8.intermediate.dense.bias
encoder.layer.8.output.dense.weight
encoder.layer.8.output.dense.bias
encoder.layer.8.output.LayerNorm.weight
encoder.layer.8.output.LayerNorm.bias
encoder.layer.9.attention.self.query.linear.weight
encoder.layer.9.attention.self.query.linear.bias
encoder.layer.9.attention.self.query.lora_a.weight
encoder.layer.9.attention.self.query.lora_b.weight
encoder.layer.9.attention.self.key.linear.weight
encoder.layer.9.attention.self.key.linear.bias
encoder.layer.9.attention.self.key.lora_a.weight
encoder.layer.9.attention.self.key.lora_b.weight
encoder.layer.9.attention.self.value.linear.weight
encoder.layer.9.attention.self.value.linear.bias
encoder.layer.9.attention.self.value.lora_a.weight
encoder.layer.9.attention.self.value.lora_b.weight
encoder.layer.9.attention.output.dense.weight
encoder.layer.9.attention.output.dense.bias
encoder.layer.9.attention.output.LayerNorm.weight
encoder.layer.9.attention.output.LayerNorm.bias
encoder.layer.9.intermediate.dense.weight
encoder.layer.9.intermediate.dense.bias
encoder.layer.9.output.dense.weight
encoder.layer.9.output.dense.bias
encoder.layer.9.output.LayerNorm.weight
encoder.layer.9.output.LayerNorm.bias
encoder.layer.10.attention.self.query.linear.weight
encoder.layer.10.attention.self.query.linear.bias
encoder.layer.10.attention.self.query.lora_a.weight
encoder.layer.10.attention.self.query.lora_b.weight
encoder.layer.10.attention.self.key.linear.weight
encoder.layer.10.attention.self.key.linear.bias
encoder.layer.10.attention.self.key.lora_a.weight
encoder.layer.10.attention.self.key.lora_b.weight
encoder.layer.10.attention.self.value.linear.weight
encoder.layer.10.attention.self.value.linear.bias
encoder.layer.10.attention.self.value.lora_a.weight
encoder.layer.10.attention.self.value.lora_b.weight
encoder.layer.10.attention.output.dense.weight
encoder.layer.10.attention.output.dense.bias
encoder.layer.10.attention.output.LayerNorm.weight
encoder.layer.10.attention.output.LayerNorm.bias
encoder.layer.10.intermediate.dense.weight
encoder.layer.10.intermediate.dense.bias
encoder.layer.10.output.dense.weight
encoder.layer.10.output.dense.bias
encoder.layer.10.output.LayerNorm.weight
encoder.layer.10.output.LayerNorm.bias
encoder.layer.11.attention.self.query.linear.weight
encoder.layer.11.attention.self.query.linear.bias
encoder.layer.11.attention.self.query.lora_a.weight
encoder.layer.11.attention.self.query.lora_b.weight
encoder.layer.11.attention.self.key.linear.weight
encoder.layer.11.attention.self.key.linear.bias
encoder.layer.11.attention.self.key.lora_a.weight
encoder.layer.11.attention.self.key.lora_b.weight
encoder.layer.11.attention.self.value.linear.weight
encoder.layer.11.attention.self.value.linear.bias
encoder.layer.11.attention.self.value.lora_a.weight
encoder.layer.11.attention.self.value.lora_b.weight
encoder.layer.11.attention.output.dense.weight
encoder.layer.11.attention.output.dense.bias
encoder.layer.11.attention.output.LayerNorm.weight
encoder.layer.11.attention.output.LayerNorm.bias
encoder.layer.11.intermediate.dense.weight
encoder.layer.11.intermediate.dense.bias
encoder.layer.11.output.dense.weight
encoder.layer.11.output.dense.bias
encoder.layer.11.output.LayerNorm.weight
encoder.layer.11.output.LayerNorm.bias
pooler.dense.weight
pooler.dense.bias

## Using transformers Trainer to fine-tune with LoRA

In [15]:
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(output_dir="test_custom_lora", 
                                  eval_strategy="steps",
                                  eval_steps= 128,
                                  num_train_epochs=2,)
trainer = Trainer(
    model=lora_model,
    args=training_args,
    train_dataset= training_set,
    eval_dataset=validation_set,
    compute_metrics=compute_metrics,
)

In [16]:
lora_train_output = trainer.train()
lora_test_results = trainer.evaluate(test_set)
# the classifier is outside lora_model.bert, so it is still trained (it is new and has to be learned)
print("Trainable parameters (LoRA + classifier):", count_trainable_parameters(lora_model))
print("Test accuracy:", lora_test_results["eval_accuracy"])

Trainable parameters (LoRA + classifier): 443906
Test accuracy: 0.879

## Using PEFT library to fine-tune with LoRA

In [17]:
from peft import LoraConfig, TaskType,  get_peft_model

lora_config = LoraConfig(
    task_type=TaskType.SEQ_CLS, r=1, lora_alpha=1, lora_dropout=0.1
)

model = BertForSequenceClassification.from_pretrained(
    'bert-base-cased', 
    num_labels=2
)
peft_model = get_peft_model(model, lora_config)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [18]:
peft_model.print_trainable_parameters()

trainable params: 38,402 || all params: 108,350,212 || trainable%: 0.0354

In [19]:
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(output_dir="test_custom_lora", 
                                  eval_strategy="steps",
                                  eval_steps= 128,
                                  num_train_epochs=2,)
trainer = Trainer(
    model=peft_model,
    args=training_args,
    train_dataset= training_set,
    eval_dataset=validation_set,
    compute_metrics=compute_metrics,
)

In [20]:
peft_train_output = trainer.train()
peft_test_results = trainer.evaluate(test_set)
print("Test accuracy:", peft_test_results["eval_accuracy"])

Test accuracy: 0.699

## Compare the results of the different approaches

In [21]:
results = [
    ("Full fine-tuning", count_trainable_parameters(full_model), full_test_results["eval_accuracy"], full_train_output.metrics["train_runtime"]),
    ("Our LoRA (r=8)", count_trainable_parameters(lora_model), lora_test_results["eval_accuracy"], lora_train_output.metrics["train_runtime"]),
    ("PEFT LoRA (r=1)", count_trainable_parameters(peft_model), peft_test_results["eval_accuracy"], peft_train_output.metrics["train_runtime"]),
]
print(f"{'Approach':<20}{'Trainable parameters':>22}{'Test accuracy':>15}{'Training time (s)':>19}")
for name, parameters, accuracy, runtime in results:
    print(f"{name:<20}{parameters:>22,}{accuracy:>15.3f}{runtime:>19.0f}")

Approach              Trainable parameters  Test accuracy  Training time (s)
Full fine-tuning               108,311,810          0.909                554
Our LoRA (r=8)                     443,906          0.879                464
PEFT LoRA (r=1)                     38,402          0.699                460

## Description of our choices

We use the same training arguments for the three approaches (2 epochs on the 5000 training reviews, with the default learning rate and batch size of the Trainer), so that only the adaptation method changes. The accuracy is computed on the 1000 test reviews, which are not the 1000 validation reviews used during training. We moved the cell defining the metric before the full fine-tuning, because it needs it.

The full fine-tuning is done on a copy of the model, so that the LoRA model starts from the pretrained BERT and not from the fine-tuned one.

In our LoRA module, the original linear layer keeps its pretrained weights and is frozen, and we add two matrices without bias: A (rank x input size) and B (output size x rank), so the output is Wx + B(Ax) as in the course. B is initialised at zero as in the LoRA paper, so at the beginning BA = 0 and the model is exactly the pretrained BERT. Like in the course, we replace the key, value and query projections of the 12 layers, with a rank of 8. The trained parameters are the LoRA matrices (12 x 3 x 8 x (768 + 768) = 442,368) and the classifier (1,538), which is outside lora_model.bert and has to be learned since it is new, so 443,906 in total.

For PEFT we kept the configuration given in the notebook (r = 1, alpha = 1). By default PEFT only adapts the query and value projections of BERT, which gives 12 x 2 x 1 x (768 + 768) + 1,538 = 38,402 trained parameters.

## Conclusion

The full fine-tuning gives the best accuracy (0.909), but it trains the 108 million parameters of BERT. Our LoRA with a rank of 8 reaches 0.879 while training only 443,906 parameters (0.4% of the model), and its validation accuracy was still slowly increasing at the end of the 2 epochs. The PEFT LoRA with a rank of 1 trains even fewer parameters (38,402) but only reaches 0.699: with a rank of 1 on two projections and the default learning rate, it does not adapt enough to the task in 2 epochs.

The training time is only slightly shorter with LoRA (464 s against 554 s), because the forward and backward passes still go through the whole network. As seen in the course, the gain of LoRA is mainly in memory: the optimizer only keeps the states of the LoRA parameters, and for a new task only A and B need to be saved. At inference, BA can be added to W, so the adapted model is not slower than the original one. So LoRA is a good choice when the model is too large to be fully fine-tuned, as long as the rank is not too small.